export type Database = {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          ticker: string;
          exchange: string;
          name: string;
          country_code: string;
          currency: string;
          sector: string | null;
          industry: string | null;
          market_cap: number | null;
          is_active: boolean;
          source: string;
          source_type: string;
          source_url: string | null;
          retrieved_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ticker: string;
          exchange: string;
          name: string;
          country_code: string;
          currency: string;
          sector?: string | null;
          industry?: string | null;
          market_cap?: number | null;
          is_active?: boolean;
          source: string;
          source_type: string;
          source_url?: string | null;
          retrieved_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ticker?: string;
          exchange?: string;
          name?: string;
          country_code?: string;
          currency?: string;
          sector?: string | null;
          industry?: string | null;
          market_cap?: number | null;
          is_active?: boolean;
          source?: string;
          source_type?: string;
          source_url?: string | null;
          retrieved_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      market_prices: {
        Row: {
          id: string;
          company_id: string;
          trade_date: string;
          currency: string;
          open: number | null;
          high: number | null;
          low: number | null;
          close: number;
          adjusted_close: number | null;
          volume: number | null;
          source: string;
          source_type: string;
          source_url: string | null;
          retrieved_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          trade_date: string;
          currency: string;
          open?: number | null;
          high?: number | null;
          low?: number | null;
          close: number;
          adjusted_close?: number | null;
          volume?: number | null;
          source: string;
          source_type: string;
          source_url?: string | null;
          retrieved_at: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          trade_date?: string;
          currency?: string;
          open?: number | null;
          high?: number | null;
          low?: number | null;
          close?: number;
          adjusted_close?: number | null;
          volume?: number | null;
          source?: string;
          source_type?: string;
          source_url?: string | null;
          retrieved_at?: string;
        };
        Relationships: [];
      };
      ai_analysis: {
        Row: {
          id: string;
          company_id: string;
          analysis_type: string;
          model_name: string;
          summary: string;
          key_findings: unknown;
          risks: unknown;
          catalysts: unknown;
          prompt_hash: string | null;
          source: string;
          source_type: string;
          source_url: string | null;
          retrieved_at: string;
          created_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          analysis_type: string;
          model_name: string;
          summary: string;
          key_findings?: unknown;
          risks?: unknown;
          catalysts?: unknown;
          prompt_hash?: string | null;
          source: string;
          source_type?: string;
          source_url?: string | null;
          retrieved_at: string;
          created_at?: string;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          analysis_type?: string;
          model_name?: string;
          summary?: string;
          key_findings?: unknown;
          risks?: unknown;
          catalysts?: unknown;
          prompt_hash?: string | null;
          source?: string;
          source_type?: string;
          source_url?: string | null;
          retrieved_at?: string;
          created_at?: string;
          expires_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
